import {afterEach,describe,expect,it,vi} from 'vitest';
import {act,create,ReactTestRenderer} from 'react-test-renderer';
import {CallbackControl,CallbackControlData} from '../src/modules/callback-control/CallbackControl';
const mocks=vi.hoisted(()=>({fetch:vi.fn(),refresh:vi.fn(),task:null as null|((s:AbortSignal)=>Promise<unknown>)}));
vi.mock('@/utils/auth-fetch',()=>({authFetch:mocks.fetch}));
vi.mock('@/utils/serial-poll',()=>({startSerialPoll:(task:(s:AbortSignal)=>Promise<unknown>)=>{mocks.task=task;return {refresh:mocks.refresh,stop:vi.fn()}}}));
vi.mock('@/components/RecordingPlayer',()=>({RecordingPlayer:()=> <div>Private recording player</div>}));
vi.mock('@/modules/phone/PhoneNumber',()=>({PhoneNumber:({phone}:{phone:string})=><button>{phone}</button>}));
let view:ReactTestRenderer|undefined;
const fixture=():CallbackControlData=>({success:true,day:'2026-10-01',today:'2026-10-01',week_start:'2026-09-27',checked_at:new Date().toISOString(),main_running:false,other_active:0,counts:{detected:9,ready:5,waiting:1,excluded:1,active:0,called:2,scheduled:1,needs_review:0},run:null,items:[{id:'entry',source_call_id:'sample-call',source_at:'2026-10-01T18:00:00Z',consumer_name:'Sample Person',phone:'+12025550123',state:'ready',blocked_reason:'',result_code:'',appointment_saved:false,attempt_call_id:null,duration_seconds:30,transcript:'Synthetic conversation'}],history:[{week_start:'2026-09-27',contacts:9,called:2}]});
afterEach(()=>{act(()=>view?.unmount());view=undefined;vi.clearAllMocks();});
async function mount(data=fixture()){mocks.fetch.mockResolvedValue({ok:true,data});await act(async()=>{view=create(<CallbackControl sessionToken="synthetic" onUnauthorized={()=>{throw Error('Unexpected logout')}}/>);await mocks.task?.(new AbortController().signal);});await act(async()=>{await mocks.task?.(new AbortController().signal);});}
const button=(label:string)=>view!.root.findAllByType('button').find(b=>b.children.includes(label))!;
describe('isolated Callback Control',()=>{
 it('shows booking readiness failures and prevents a start request',async()=>{await mount({...fixture(),booking_block:'1 overdue appointment needs James’s review.'});expect(button('Start callbacks').props.disabled).toBe(true);expect(JSON.stringify(view!.toJSON())).toContain('Appointments need attention');await act(async()=>await button('Start callbacks').props.onClick());expect(mocks.fetch.mock.calls.every(c=>c[1].body.action==='callback_control_status')).toBe(true);});
 it('loads without starting calls, opening the phone or playing a recording',async()=>{await mount();expect(mocks.fetch.mock.calls.every(c=>c[1].body.action==='callback_control_status')).toBe(true);const text=JSON.stringify(view!.toJSON());expect(text).toContain('Callback Control');expect(text).toContain('Appointments saved');expect(text).not.toContain('Private recording player');expect(button('Start callbacks').props.disabled).toBe(false);});
 it('blocks Start while main dialer is running or other calls are finishing',async()=>{await mount({...fixture(),main_running:true});expect(button('Start callbacks').props.disabled).toBe(true);expect(JSON.stringify(view!.toJSON())).toContain('Stop it above');});
 it('requires one explicit Start and carries selected maximum without starting main campaign',async()=>{await mount();await act(async()=>view!.root.findByType('select').props.onChange({target:{value:'12'}}));await act(async()=>await button('Start callbacks').props.onClick());const mutations=mocks.fetch.mock.calls.filter(c=>c[1].body.action!=='callback_control_status');expect(mutations).toHaveLength(1);expect(mutations[0][1].body).toMatchObject({action:'callback_control_start',lines:12});});
 it('Stop remains available during a refresh failure and does not clear data',async()=>{await mount({...fixture(),run:{id:'run',state:'running',work_day:'2026-10-01',lines:3,reason:'Calling eligible contacts',created_at:'2026-10-01T18:00:00Z',last_tick_at:null}});mocks.fetch.mockResolvedValue({ok:false,error:'Temporary outage'});await act(async()=>{await mocks.task?.(new AbortController().signal)});expect(button('Stop callbacks').props.disabled).toBe(false);expect(button('Start callbacks').props.disabled).toBe(true);await act(async()=>await button('Stop callbacks').props.onClick());expect(mocks.fetch.mock.calls.at(-1)![1].body.action).toBe('callback_control_stop');});
 it('shows history but never enables Start for earlier dates',async()=>{await mount({...fixture(),day:'2026-09-30'});expect(button('Start callbacks').props.disabled).toBe(true);expect(JSON.stringify(view!.toJSON())).toContain('History view only');});
 it('recordings require a deliberate click and do not mutate callback completion',async()=>{await mount();await act(async()=>button('View contacts & recordings').props.onClick());expect(JSON.stringify(view!.toJSON())).not.toContain('Private recording player');await act(async()=>button('Listen to original call').props.onClick());expect(JSON.stringify(view!.toJSON())).toContain('Private recording player');expect(mocks.fetch.mock.calls.every(c=>c[1].body.action==='callback_control_status')).toBe(true);});
});
