import { startSerialPoll } from '@/utils/serial-poll';
import { useEffect, useState } from 'react';
import { monitoringRequest, costaRicaDay } from './api';
import { PhoneNumber } from '@/modules/phone/PhoneNumber';
import './monitoring.css';
type Agent = { id:string; full_name:string; presence:string; current_since:string|null; last_seen_at:string|null; logged_seconds:number; outbound_calls:number; outbound_answered:number; inbound_answered:number; transfers_received:number; transfers_answered:number; voicemail_visits:number; unknown_direction:number; connected_seconds:number; average_seconds:number|null; short_calls:number; callbacks_assigned:number; callbacks_attempted:number; callbacks_pending:number; transfers_sent:number; transfers_pending_callback:number; current_login_seconds:number|null; week_logged_seconds:number };
type Call = { pbx_call_id:string; started_at:string; answered_at:string|null; ended_at:string|null; disposition:string; voicemail_reached:boolean; kind:string; phone:string; connected_seconds:number|null; ring_seconds:number|null; recording_available:boolean };
type Callback = { source_id:string; name:string; phone:string; created_at:string; completed:boolean; reason:string; attempt_id:string|null; attempted_at:string|null };
type Report = { day:string; server_now:string; attendance_enabled_at:string; agents:Agent[]; calls:Call[]; calls_total:number; callbacks:Callback[]; callbacks_total:number; transfer_backlog_total:number;transfer_backlog:{source_id:string;name:string;phone:string;created_at:string}[]; intervals:{started_at:string; ended_at:string;last_seen_at:string}[] };
const agentColors = ['#67b7ff','#c49aff','#ffbe67','#60dbc1','#fa91bc','#d6de76','#91a8ff'];
const duration = (seconds?:number|null) => seconds == null ? '—' : `${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${Math.round(seconds%60)}s`;
const time = (value?:string|null) => value ? new Date(value).toLocaleTimeString('en-US',{timeZone:'America/Costa_Rica',hour:'numeric',minute:'2-digit',second:'2-digit'}) : '—';
export function AgentMonitoring({ token }: { token:string }) {
 const [day,setDay]=useState(costaRicaDay); const [agent,setAgent]=useState(''); const [tab,setTab]=useState('calls'); const [offset,setOffset]=useState(0);
 const [report,setReport]=useState<Report|null>(null); const [error,setError]=useState(''); const [refresh,setRefresh]=useState(0);
 useEffect(()=>{
  setReport(null);
  const poll=startSerialPoll(async signal=>{
   try { const data=await monitoringRequest(token,{action:'report',day,agent_id:agent||null,offset},signal); if(signal.aborted)return false; setReport(data);setError('');return true; }
   catch(e){if(!signal.aborted)setError(e instanceof Error?e.message:'Monitoring unavailable');return false;}
  },30000,{paused:()=>document.hidden,maxBackoffMs:120000});
  const resume=()=>{if(!document.hidden)poll.refresh();};
  window.addEventListener('online',resume);document.addEventListener('visibilitychange',resume);
  return()=>{poll.stop();window.removeEventListener('online',resume);document.removeEventListener('visibilitychange',resume);};
 },[token,day,agent,offset,refresh]);
 const selected=report?.agents.find(a=>a.id===agent);
 return <section className="f1-monitor">
  <header><div><small>YOUR TEAM</small><h1>Team Monitor</h1><p>Who is here and how their calls are going</p></div><div><label>Choose a day <input type="date" min="2026-09-25" max={costaRicaDay()} value={day} onChange={e=>{setDay(e.target.value);setOffset(0);}} /></label><button onClick={()=>setRefresh(v=>v+1)}>Update now</button></div></header>
  {error && <p role="alert" className="f1-monitor-error">{error}. Displayed results may be stale. Calling is unaffected.</p>}
  {!report && !error && <p role="status">Loading monitoring records…</p>}
  {report && <>
   <div className="f1-team-summary"><strong>{error?'Live status unknown':`${report.agents.filter(a=>a.presence!=='Not reporting').length} logged in`}</strong>{!error&&<span>{report.agents.filter(a=>a.presence==='Not reporting').length} not logged in</span>}<small>Updated {time(report.server_now)} · Costa Rica time</small></div>
   <p>Choose an agent to see their calls and time logged in.</p>
   <div className="f1-agent-cards">{report.agents.map((a,index)=>{
    const online=!error && a.presence!=='Not reporting';
    const color=agentColors[index%agentColors.length];
    return <button type="button" key={a.id} className={`f1-agent-card ${agent===a.id?'chosen':''}`} style={{borderTopColor:color}} onClick={()=>{setAgent(a.id);setOffset(0);}} aria-pressed={agent===a.id}>
     <div className="f1-agent-heading"><span className="f1-agent-avatar" style={{background:color,color:'#102132'}}>{a.full_name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><strong>{a.full_name}</strong></div>
     <span className={`f1-login-status ${online?'online':'offline'}`}>{error?'Status unknown':online?'● Logged in':'○ Not logged in'}{a.presence==='Away'?' · Away from desk':''}</span>
     <small>{online?`Logged in since ${time(a.current_since)}`:a.last_seen_at?`Last seen ${time(a.last_seen_at)}`:'No login recorded yet'}</small>
     <div className="f1-agent-hours"><strong>{duration(a.logged_seconds)}</strong><span>Time logged in on selected day · recorded</span><small>Current login: {online?duration(a.current_login_seconds):'Not logged in'}<br/>Week through selected day: {a.week_logged_seconds?duration(a.week_logged_seconds):'Not tracked yet'}</small></div>
     <dl><div><dt>Calls made from phone</dt><dd>{a.outbound_calls}</dd></div><div><dt>Incoming calls answered</dt><dd>{a.inbound_answered+a.transfers_answered}</dd></div><div><dt>Transfers requested</dt><dd>{a.transfers_sent}</dd></div><div><dt>Transfers reached phone</dt><dd>{a.transfers_received}</dd></div><div><dt>Agent pickups recorded</dt><dd>{a.transfers_answered}</dd></div><div><dt>Transfers needing a callback</dt><dd>{a.transfers_pending_callback}</dd></div></dl>
     <span className="f1-agent-open">See details →</span>
    </button>;
   })}</div>
   <details className="f1-monitor-explainer"><summary>How these numbers work</summary><p>Login status updates about every 30 seconds. After 90 seconds without a signal, we show “Not logged in.” A lost internet connection can cause this too. Login time does not prove the agent is working or that their phone is ready.</p><p>Weekly time starts Monday and includes only recorded hours. Tracking began {new Date(report.attendance_enabled_at).toLocaleString('en-US',{timeZone:'America/Costa_Rica'})}. Earlier time is unknown. Calls made counts agent phone calls, not the automatic dialer. Transfers requested includes inbound and outbound conversations; Call Reports counts outbound requests only. Answered calls use the phone provider’s records; audio has not been checked.</p></details>
   {selected ? <div className="f1-monitor-detail"><h2>{selected.full_name} — Details</h2><div className="f1-detail-totals"><span><strong>{duration(selected.average_seconds)}</strong>Average call length</span><span><strong>{selected.short_calls}</strong>Calls under 15 seconds</span><span><strong>{selected.callbacks_assigned}</strong>People assigned to call</span><span><strong>{selected.callbacks_attempted}</strong>People called back</span></div><p>Short calls are worth reviewing. They do not prove the agent hung up.</p><nav>{['calls','pending','callbacks','attendance'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>{setTab(t);setOffset(0);}}>{t==='calls'?'Call history':t==='pending'?'Transfers needing callbacks':t==='callbacks'?'Other callback records':'Login times'}</button>)}</nav>
    {tab==='calls' && <div className="f1-monitor-table"><table><thead><tr><th>Time</th><th>Call / number</th><th>What happened</th><th>Ring time</th><th>Time connected</th><th>More information</th></tr></thead><tbody>{report.calls.map(c=><tr key={c.pbx_call_id}><td>{time(c.started_at)}</td><td>{c.kind==='outbound'?'Agent called out':c.kind==='inbound'?'Incoming call':c.kind==='transfer'?'Transferred call':'Call type unknown'}<br/><PhoneNumber phone={c.phone}/></td><td>{c.voicemail_reached?'Voicemail greeting':c.disposition||'Unknown'}{!c.ended_at?' · In progress':''}</td><td>{duration(c.ring_seconds)}</td><td>{duration(c.connected_seconds)}</td><td><details><summary>Call details</summary><small>Reference {c.pbx_call_id}<br/>{c.recording_available?'Recording reference available':'No recording reference'}<br/>Who ended the call: unknown</small></details></td></tr>)}</tbody></table>{!report.calls.length&&<p>No calls recorded for this selection.</p>}</div>}
    {tab==='pending' && <><p>Unreturned transfers through the selected day, including earlier days. A later outgoing call removes the number from this list; it does not prove the client answered. Completed, dismissed, do-not-call and wrong-number records are excluded where recorded.</p><div className="f1-monitor-table"><table><thead><tr><th>Received</th><th>Person / number</th><th>Next step</th></tr></thead><tbody>{report.transfer_backlog.map(c=><tr key={c.source_id}><td>{new Date(c.created_at).toLocaleString('en-US',{timeZone:'America/Costa_Rica'})}</td><td>{c.name||'Client'}<br/><PhoneNumber phone={c.phone}/></td><td>No callback attempt recorded</td></tr>)}</tbody></table>{!report.transfer_backlog.length&&<p>No transfers awaiting a first callback attempt.</p>}</div></>}
    {tab==='callbacks' && <><p>These people were listed for a callback. “Called back” means an outgoing call was placed to their number, not necessarily answered. Each person is counted once per agent for the selected day.</p><div className="f1-monitor-table"><table><thead><tr><th>Assigned</th><th>Client</th><th>Reason</th><th>Follow-through</th></tr></thead><tbody>{report.callbacks.map(c=><tr key={c.source_id}><td>{time(c.created_at)}</td><td>{c.name||'Client'}<br/><PhoneNumber phone={c.phone}/></td><td>{c.reason}</td><td>{c.completed?'Marked complete':c.attempt_id?`Called back ${time(c.attempted_at)}`:'Still to call'}</td></tr>)}</tbody></table>{!report.callbacks.length&&<p>No callback assignments recorded for this selection.</p>}</div></>}
    {tab==='attendance' && <><p>Times below show when the app reported this agent logged in. Allow up to 90 seconds for a logout or disconnection to appear.</p><ul>{report.intervals.map(i=><li key={i.started_at}>{time(i.started_at)} – {time(i.ended_at)} · Last update {time(i.last_seen_at)}</li>)}</ul>{!report.intervals.length&&<p>No attendance reported yet. The agent must open the updated app.</p>}</>}
    {tab!=='attendance'&&<footer><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous</button><span>{(tab==='calls'?report.calls_total:tab==='pending'?report.transfer_backlog_total:report.callbacks_total) ? offset+1 : 0}–{Math.min(offset+100,tab==='calls'?report.calls_total:tab==='pending'?report.transfer_backlog_total:report.callbacks_total)} of {tab==='calls'?report.calls_total:tab==='pending'?report.transfer_backlog_total:report.callbacks_total}</span><button disabled={offset+100>=(tab==='calls'?report.calls_total:tab==='pending'?report.transfer_backlog_total:report.callbacks_total)} onClick={()=>setOffset(offset+100)}>Next</button></footer>}
   </div>:<p>Select an agent above to see more.</p>}
  </>}
 </section>;
}
