import { useEffect, useState } from 'react';
import { monitoringRequest, costaRicaDay } from './api';
import { PhoneNumber } from '@/modules/phone/PhoneNumber';
import './monitoring.css';
type Agent = { id:string; full_name:string; presence:string; current_since:string|null; last_seen_at:string|null; logged_seconds:number; outbound_calls:number; outbound_answered:number; inbound_answered:number; transfers_received:number; transfers_answered:number; voicemail_visits:number; unknown_direction:number; connected_seconds:number; average_seconds:number|null; short_calls:number; callbacks_assigned:number; callbacks_attempted:number; callbacks_pending:number };
type Call = { pbx_call_id:string; started_at:string; answered_at:string|null; ended_at:string|null; disposition:string; voicemail_reached:boolean; kind:string; phone:string; connected_seconds:number|null; ring_seconds:number|null; recording_available:boolean };
type Callback = { source_id:string; name:string; phone:string; created_at:string; completed:boolean; reason:string; attempt_id:string|null; attempted_at:string|null };
type Report = { day:string; server_now:string; attendance_enabled_at:string; agents:Agent[]; calls:Call[]; calls_total:number; callbacks:Callback[]; callbacks_total:number; intervals:{started_at:string; ended_at:string;last_seen_at:string}[] };
const duration = (seconds?:number|null) => seconds == null ? '—' : `${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${Math.round(seconds%60)}s`;
const time = (value?:string|null) => value ? new Date(value).toLocaleTimeString('en-US',{timeZone:'America/Costa_Rica',hour:'numeric',minute:'2-digit',second:'2-digit'}) : '—';
export function AgentMonitoring({ token }: { token:string }) {
 const [day,setDay]=useState(costaRicaDay); const [agent,setAgent]=useState(''); const [tab,setTab]=useState('calls'); const [offset,setOffset]=useState(0);
 const [report,setReport]=useState<Report|null>(null); const [error,setError]=useState(''); const [refresh,setRefresh]=useState(0);
 useEffect(()=>{
  const controller=new AbortController(); let pending=false;
  const load=async()=>{ if(pending) return; pending=true; try { const data=await monitoringRequest(token,{action:'report',day,agent_id:agent||null,offset},controller.signal); if(!controller.signal.aborted){setReport(data);setError('');} } catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Monitoring unavailable');} finally{pending=false;} };
  setReport(null); void load(); const timer=window.setInterval(()=>{if(!document.hidden)void load();},30000);
  return()=>{controller.abort();window.clearInterval(timer);};
 },[token,day,agent,offset,refresh]);
 const selected=report?.agents.find(a=>a.id===agent);
 return <section className="f1-monitor">
  <header><div><small>SUPERVISOR WORKSPACE</small><h1>Agent Monitoring</h1><p>Attendance, received calls and follow-through · Costa Rica time</p></div><div><label>Day <input type="date" min="2026-09-25" max={costaRicaDay()} value={day} onChange={e=>{setDay(e.target.value);setOffset(0);}} /></label><button onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div></header>
  {error && <p role="alert" className="f1-monitor-error">{error}. Displayed results may be stale. Calling is unaffected.</p>}
  {!report && !error && <p role="status">Loading monitoring records…</p>}
  {report && <>
   <p className="f1-monitor-note">Attendance starts with the new page version from {new Date(report.attendance_enabled_at).toLocaleString('en-US',{timeZone:'America/Costa_Rica'})}. Earlier time is unknown. Login time measures app presence, not work or phone readiness; reconnect gaps over 90 seconds are excluded. Multiple tabs do not add time twice.</p>
   <small>Updated {time(report.server_now)} · Refreshes every 30 seconds while visible</small>
   <div className="f1-monitor-table"><table><thead><tr>{['Agent','Presence','Logged in today','Current session','Outbound placed / answered','Inbound answered','Transfers received / answered','Callbacks assigned / attempted / pending','Avg. connected','Short calls'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{report.agents.map(a=><tr key={a.id} className={agent===a.id?'selected':''}><td><button onClick={()=>{setAgent(a.id);setOffset(0);}}>{a.full_name}</button></td><td>{a.presence}<small>Last seen {time(a.last_seen_at)}</small></td><td>{duration(a.logged_seconds)}</td><td>{time(a.current_since)}</td><td>{a.outbound_calls} / {a.outbound_answered}</td><td>{a.inbound_answered}</td><td>{a.transfers_received} / {a.transfers_answered}</td><td>{a.callbacks_assigned} / {a.callbacks_attempted} / {a.callbacks_pending}</td><td>{duration(a.average_seconds)}</td><td>{a.short_calls}</td></tr>)}</tbody></table></div>
   <p className="f1-monitor-note">Outbound counts are agent-line provider records, separate from automated campaign attempts. “Answered” means a provider answer without a voicemail flag, not verified two-way conversation. Connected time excludes ringing. Calls under 15 connected seconds are review flags, not proof an agent hung up.</p>
   {selected ? <div className="f1-monitor-detail"><h2>{selected.full_name}</h2><p>{duration(selected.connected_seconds)} connected · {selected.voicemail_visits} voicemail visits · {selected.unknown_direction} unknown-direction records</p><nav>{['calls','callbacks','attendance'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>{setTab(t);setOffset(0);}}>{t}</button>)}</nav>
    {tab==='calls' && <div className="f1-monitor-table"><table><thead><tr><th>Started</th><th>Type / number</th><th>Outcome</th><th>Ring time</th><th>Connected time</th><th>Evidence</th></tr></thead><tbody>{report.calls.map(c=><tr key={c.pbx_call_id}><td>{time(c.started_at)}</td><td>{c.kind}<br/><PhoneNumber phone={c.phone}/></td><td>{c.voicemail_reached?'Voicemail greeting':c.disposition||'Unknown'}{!c.ended_at?' · In progress':''}</td><td>{duration(c.ring_seconds)}</td><td>{duration(c.connected_seconds)}</td><td><small>Provider record {c.pbx_call_id}<br/>{c.recording_available?'Recording reference available':'No recording reference'}<br/>Who ended the call: unknown</small></td></tr>)}</tbody></table>{!report.calls.length&&<p>No calls recorded for this selection.</p>}</div>}
    {tab==='callbacks' && <><p>Assignments include system-flagged human opportunities, which may need review for machine false positives. They are deduplicated by agent and number. “Attempted” matches a later provider outbound attempt to that number; it does not mean the client answered or the task was resolved.</p><div className="f1-monitor-table"><table><thead><tr><th>Assigned</th><th>Client</th><th>Reason</th><th>Follow-through</th></tr></thead><tbody>{report.callbacks.map(c=><tr key={c.source_id}><td>{time(c.created_at)}</td><td>{c.name||'Client'}<br/><PhoneNumber phone={c.phone}/></td><td>{c.reason}</td><td>{c.completed?'Marked complete':c.attempt_id?`Attempted ${time(c.attempted_at)}`:'Pending attempt'}</td></tr>)}</tbody></table>{!report.callbacks.length&&<p>No callback assignments recorded for this selection.</p>}</div></>}
    {tab==='attendance' && <><p>Each interval ends at the last heartbeat plus up to 90 seconds, capped at the current time and day boundary.</p><ul>{report.intervals.map(i=><li key={i.started_at}>{time(i.started_at)} – {time(i.ended_at)} · Last heartbeat {time(i.last_seen_at)}</li>)}</ul>{!report.intervals.length&&<p>No attendance reported yet. The agent must open the updated app.</p>}</>}
    {tab!=='attendance'&&<footer><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous</button><span>{(tab==='calls'?report.calls_total:report.callbacks_total) ? offset+1 : 0}–{Math.min(offset+100,tab==='calls'?report.calls_total:report.callbacks_total)} of {tab==='calls'?report.calls_total:report.callbacks_total}</span><button disabled={offset+100>=(tab==='calls'?report.calls_total:report.callbacks_total)} onClick={()=>setOffset(offset+100)}>Next</button></footer>}
   </div>:<p>Select an agent to inspect individual calls, callback assignments and attendance intervals.</p>}
  </>}
 </section>;
}
