import { useEffect, useState } from 'react';
import { monitoringRequest, costaRicaDay } from './api';
import './monitoring.css';
type SnapshotAgent={id:string;full_name:string;presence:string;outbound_calls:number;callbacks_pending:number;logged_seconds:number;transfers_sent:number;transfers_received:number;transfers_answered:number;transfers_pending_callback:number;current_login_seconds:number|null;week_logged_seconds:number};
const hours=(seconds:number|null)=>seconds==null?'Not tracked yet':`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;
const colors=['#67b7ff','#c49aff','#ffbe67','#60dbc1','#fa91bc','#d6de76','#91a8ff'];
export function TeamSnapshot({token,onOpen}:{token:string;onOpen:()=>void}) {
 const [agents,setAgents]=useState<SnapshotAgent[]>([]);const [updated,setUpdated]=useState('');const [error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();let pending=false;
 const load=async()=>{if(pending)return;pending=true;try{const data=await monitoringRequest(token,{action:'report',day:costaRicaDay()},controller.signal);if(!controller.signal.aborted){setAgents(data.agents);setUpdated(data.server_now);setError('');}}catch{if(!controller.signal.aborted)setError('Team status is unavailable. Open Monitoring to try again.');}finally{pending=false;}};
 void load();const timer=window.setInterval(()=>{if(!document.hidden)void load();},30000);return()=>{controller.abort();window.clearInterval(timer);};},[token]);
 return <section className="f1-team-snapshot" aria-label="Quick team monitor"><header><div><small>TEAM AT A GLANCE</small><h2>Who’s here today?</h2><p>{updated?`${agents.filter(a=>a.presence!=='Not reporting').length} logged in · ${agents.length} agents`:'Checking your team…'}</p></div><button type="button" onClick={onOpen}>Open Monitoring →</button></header>
 {error&&<p role="alert">{error} Previous numbers may be out of date.</p>}
 <div className="f1-snapshot-grid">{agents.map((a,i)=>{const online=a.presence!=='Not reporting';return <button type="button" key={a.id} onClick={onOpen} style={{borderTopColor:colors[i%colors.length]}} aria-label={`Open monitoring for ${a.full_name}`}><strong className="f1-snapshot-name">{a.full_name}</strong><span className={`f1-login-status ${online?'online':'offline'}`}>{error?'Status unavailable':online?'● Logged in':'○ Not logged in'}</span>{online&&a.presence==='Away'&&<small>Away from desk</small>}<dl><div><dt>Transfers sent today</dt><dd>{a.transfers_sent}</dd></div><div><dt>Transfers that reached phone</dt><dd>{a.transfers_received}</dd></div><div><dt>Transfers answered</dt><dd>{a.transfers_answered}</dd></div><div><dt>Calls made from phone today</dt><dd>{a.outbound_calls}</dd></div><div className="f1-pending-callbacks"><dt>Transfers still needing a callback</dt><dd>{a.transfers_pending_callback}</dd></div></dl><div className="f1-snapshot-times"><span><small>Current login</small><strong>{online?hours(a.current_login_seconds):'Not logged in'}</strong></span><span><small>Logged in today · recorded</small><strong>{a.logged_seconds?hours(a.logged_seconds):'Not tracked yet'}</strong></span><span><small>Logged in this week · recorded</small><strong>{a.week_logged_seconds?hours(a.week_logged_seconds):'Not tracked yet'}</strong></span></div></button>;})}</div>
 <footer>Pending callbacks include older transfers with no later outgoing call recorded and no completed or dismissed task. Calling back does not mean the person answered. Weekly time starts Monday, but recording began September 25; earlier hours are unknown. “Logged in” does not mean the agent is on a call. Status updates may take 90 seconds.{updated&&` Updated ${new Date(updated).toLocaleTimeString('en-US',{timeZone:'America/Costa_Rica',hour:'numeric',minute:'2-digit'})}.`}</footer>
 </section>;
}
